name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  words:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Count words
        run: make count
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          files: source/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
