name: Continuous Delivery

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
      - name: Build book (PDF + EPUB)
        run: nix build .#book -L
      - name: Archive PDF
        uses: actions/upload-artifact@v7
        with:
          name: pdf
          path: result/book.pdf
      - name: Archive EPUB
        uses: actions/upload-artifact@v7
        with:
          name: epub
          path: result/book.epub
